name: CI/CD to EC2

on:
  push:
    branches:
      - CICD # Deploy when main is updated

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest
          docker stop backend frontend || true
          docker rm backend frontend || true
          docker run -d -p 8000:8000 --name backend ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest
          docker run -d -p 80:80 --name frontend --link backend ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest
